### PR TITLE
Propose Code of Conduct

### PR DESCRIPTION
**Pull request by AurumByte**
# Propose Code of Conduct

Code of Conduct for FastJ.... Review needed to finalize...

### CODE REVIEW

**Comment by lucasstarsz** [comment]
I'm currently having issues with SonarCloud not working for developers other than myself. When I have an update on the situation, I will let you know.

**Review by lucasstarsz — APPROVED** [review]
This seems good to me.

**Comment by AurumByte** [comment]
Cool.

**Comment by lucasstarsz** [comment]
As far as I can tell, I have fixed issues with permissions for running code analysis. If anything, I will make sure of this in the next pull requests. I apologize for any inconvenience this might have caused you.

With that said, this pull request is fine to be merged.

**Pull request merged**
